[tool.poetry]
name = "googleapiutils"
version = "0.2.1"
description = ""
authors = ["Mike Babb <mike7400@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
google-auth-httplib2 = "^0.1.0"
google-auth-oauthlib = "^0.5.1"
google-api-python-client = "^2.47.0"
requests = "^2.28.1"
pandas = {version = "^1.4.3", optional = true}

[tool.poetry.dev-dependencies]
black = "^22.6.0"
google-api-python-client-stubs = "^1.11.0"
types-requests = "^2.28.9"
mypy = "^0.971"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
